import io
import pandas as pd
from typing import Dict, Any, List

def export_df_to_csv(df: pd.DataFrame) -> bytes:
    """
    Converts a pandas dataframe to CSV bytes for download.
    """
    return df.to_csv(index=False).encode("utf-8")

def generate_kpi_summary_report(kpis: Dict[str, Any], health: Dict[str, Any]) -> str:
    """
    Generates a structured text/markdown executive summary for download.
    """
    lines = [
        "# 🚀 InsightIQ - Executive Business Intelligence Report",
        f"Generated Timestamp: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 1. Executive KPIs",
        f"- Total Revenue: ₹{kpis.get('total_revenue', 0):,.2f}",
        f"- Total Orders: {kpis.get('total_orders', 0):,}",
        f"- Average Order Value: ₹{kpis.get('avg_order_value', 0):,.2f}",
        f"- Month-over-Month Growth: {kpis.get('growth_mom', 0):+.2f}%",
        f"- Active Regions: {kpis.get('active_regions', 0)}",
        f"- Active Categories: {kpis.get('active_products', 0)}",
        "",
        f"## 2. Business Health Scorecard ({health.get('overall_score', 0)}/100)",
    ]

    for p in health.get("pillars", []):
        lines.append(f"- {p['name']}: {p['badge']} ({p['metric']}) - {p['diagnostic']}")

    lines.append("")
    lines.append("---")
    lines.append("Generated by InsightIQ - AI Business Intelligence & Decision Intelligence Platform")
    return "\n".join(lines)
